### ISSUE TITLE
It doesn't work

### ISSUE THREAD

**Issue by DakotaRobey** [DrewBarrett/cpp-final#1]
We need to make this project work or we are gonna fail and neoiafvuh80edbcefuyvcnpioj98ufhydasp98uch87e0hafduipashcnu87ozxh7d89awo7heiuofdsayh908hp
![gasmask](https://cloud.githubusercontent.com/assets/16539722/14673017/5a930780-06c9-11e6-9618-8e8da28d74dd.jpg)

**Comment by DrewBarrett** [comment]
no
maybe
yes
